### ISSUE TITLE
Failed to parse total/available money (VirementError)

### ISSUE THREAD

**Issue by n-eq** [kalidor/blablacar#1]
Hi, 

When I try to execute the script in order to list my messages/notifications I'm able to successfully log in but I always get this problem:
`lib/notifications.rb:259:in total_and_current: Failed to parse total/available money (VirementError)`

![image](https://cloud.githubusercontent.com/assets/16545838/24330048/977e8f62-1216-11e7-933e-f5612a3afcd0.png)

**Comment by kalidor** [comment]
Yeah the parser cannot match the regex. Nothing hard to fix. I will fix that as soon as i get back home (in a week)

**Comment by kalidor** [comment]
Should be fixed. If not, reopen this ticket and copy & paste the HTML code containing the message with the amount available, of the following link [https://www.blablacar.fr/dashboard/account/money-available](url) when you are authenticated. I don't have available money myself right now.
